name: Run Continuous Integration Tests

on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main

jobs:
  uv-tox-ci:
    name: UV Tox CI Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Install a specific version of uv.
          version: "0.10.7"

      - name: Run UV Tox
        run: uv run tox p
